configuration: Release
platform: Any CPU
image: Visual Studio 2017

install:
  - set PATH=C:\Ruby23\bin;%PATH%
  - ps: $AllProtocols = [System.Net.SecurityProtocolType]'Ssl3,Tls,Tls11,Tls12'
  - ps: "[System.Net.ServicePointManager]::SecurityProtocol = $AllProtocols"
  - ps: mkdir c:\ca; iwr http://curl.haxx.se/ca/cacert.pem -outfile C:\ca\cacert.pem
  - set SSL_CERT_FILE=C:\ca\cacert.pem
  - ps: |
        $version = [version]$(cat VERSION)
        $build = $env:APPVEYOR_BUILD_NUMBER
        $major = $version.Major
        $branch = $env:APPVEYOR_REPO_BRANCH
        echo "VERSION: $version, build: $build, major: $major, branch: $branch"
        if ($branch -eq 'master') {
          $version = "$version-ci-$build"
        } elseif ($env:APPVEYOR_REPO_TAG -ne "") {
          echo "Setting to tag name"
          $version = $env:APPVEYOR_REPO_TAG_NAME
        }
        else {
          $version = "$version-br-$branch-$build"
        }
        echo "Version is $version"
        Set-AppveyorBuildVariable -Name "AssemblyMajor" -Value "$major"
        Update-AppVeyorBuild -Version "$version"

  - gem install chandler --no-ri --no-rdoc
  - ps: set-content ~/.netrc "machine api.github.com login $env:github_username password $env:github_password" -encoding ascii
  - ps: cp ~/.netrc ~/_netrc
  - chandler push

assembly_info:
  patch: true
  file: src\CommonInfo.cs
  assembly_version: $(AssemblyMajor).0.0.0
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}'

before_build:
  - nuget restore src


environment:
  SSL_CERT_FILE: C:\ca\cacert.pem
  github_username: serialseb
  github_password:
    secure:
      1lXaOJ0GvCAOd0O9DDvVqw2eb7TvP2jve12u3hD2g4J7RVW2c2jC5XuRFyEuduUA


nuget:
  project_feed: true
  disable_publish_on_pr: true


build:
  publish_nuget: true
  publish_nuget_symbols: true
  include_nuget_references: true
  verbosity: minimal

test:
  assemblies: 
   - src\OpenRasta.Hosting.AspNet.Tests.Integration\bin\$(configuration)\OpenRasta.Hosting.AspNet.Tests.Integration.dll
   - src\Tests\bin\$(configuration)\Tests.dll

artifacts:
- path: src\OpenRasta.Hosting.AspNet\bin\$(configuration)\*.dll
  name: dlls
- path: src\OpenRasta.Hosting.AspNet\bin\$(configuration)\*.pdb
  name: pdbs
